name: CI/CD Pipeline

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  test-and-deploy:
    runs-on: self-hosted  # This uses your self-hosted runner
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.10'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install pytest

      - name: Run unit tests
        run: |
          pytest tests/test_app.py

      - name: Run integration tests
        run: |
          pytest tests/test_integration.py

      - name: Deploy (pull latest code and restart app)
        if: success()
        run: |
          git pull origin main
          pip install -r requirements.txt
          sudo supervisorctl restart pdf-extractor
       