name: CI/CD Pipeline

on:
  workflow_run:
    workflows: ["EPA PDF Extractor application"]
    types:
      - completed

jobs:
  test:
    if: ${{ github.event.workflow_run.conclusion == 'success' }}
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.10'
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
          pip install pytest
      - name: Run unit tests
        run: pytest tests/test_app.py
      - name: Run integration tests
        run: pytest tests/test_integration.py

  deploy:
    needs: test
    runs-on: self-hosted
    if: github.ref == 'refs/heads/main' && github.event_name == 'push'
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Install dependencies
        run: |
          pip install -r requirements.txt

      - name: Update code
        run: |
          cd /home/webapps/pdf-extractor
          git pull --no-rebase

      - name: Restart app
        run: sudo supervisorctl restart pdf-extractor
